-- Synthetic schema1 generated by the pre-update repository; no user data.
BEGIN TRANSACTION;
CREATE TABLE assignments (
                    group_id        TEXT PRIMARY KEY,
                    classroom_name  TEXT NOT NULL,
                    day             INTEGER NOT NULL,
                    start_min       INTEGER NOT NULL,
                    end_min         INTEGER NOT NULL,
                    lab_override    INTEGER NOT NULL DEFAULT 0
                );
INSERT INTO "assignments" VALUES('MAT-G1','Aula Á',1,420,480,1);
CREATE TABLE classrooms (
                    name        TEXT PRIMARY KEY,
                    capacity    INTEGER NOT NULL,
                    room_type   TEXT NOT NULL,
                    description TEXT DEFAULT '',
                    campus      TEXT DEFAULT ''
                );
INSERT INTO "classrooms" VALUES('Aula Á',30,'REGULAR','Sintético','Campus Ñ');
CREATE TABLE course_group_suggestions (
                    course_code         TEXT NOT NULL,
                    group_index         INTEGER NOT NULL,
                    aula                TEXT,
                    preferred_day       TEXT,
                    preferred_start_min INTEGER,
                    PRIMARY KEY (course_code, group_index)
                );
INSERT INTO "course_group_suggestions" VALUES('MAT',0,'Aula Á','Lunes',420);
CREATE TABLE courses (
                    code                TEXT PRIMARY KEY,
                    name                TEXT,
                    number_of_groups    INTEGER NOT NULL,
                    duration_min        INTEGER NOT NULL,
                    required_room_type  TEXT NOT NULL,
                    size                INTEGER NOT NULL DEFAULT 0,
                    suggested_classroom TEXT,
                    preferred_day       TEXT,
                    preferred_start_min INTEGER,
                    force_split         INTEGER  -- NULL=auto, 1=force, 0=never
                );
INSERT INTO "courses" VALUES('MAT','Matemática',1,60,'LAB',24,'Aula Á','Lunes',420,0);
CREATE TABLE restrictions (
                    classroom_name  TEXT NOT NULL,
                    course_code     TEXT NOT NULL,
                    PRIMARY KEY (classroom_name, course_code)
                );
INSERT INTO "restrictions" VALUES('Aula Á','MAT');
CREATE TABLE session (
                    id          INTEGER PRIMARY KEY CHECK (id = 1),
                    excel_path  TEXT,
                    seed        INTEGER,
                    saved_at    TEXT DEFAULT (datetime('now'))
                );
INSERT INTO "session" VALUES(1,'Café.xlsx',17,'2026-10-03 01:09:27');
COMMIT;
PRAGMA user_version=1;
